# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_flames(object):
    def setupUi(self, flames):
        flames.setObjectName("flames")
        flames.resize(800, 600)
        flames.setStyleSheet("""
            background-color: rgb(170, 175, 175); 
        """)
        self.labelname1 = QtWidgets.QLabel(parent=flames)
        self.labelname1.setGeometry(QtCore.QRect(140, 120, 49, 21))
        self.labelname1.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.labelname1.setObjectName("labelname1")
        self.labelname1.setStyleSheet("background-color: rgb(123, 123, 123);color: black; font-size: 14px;")

        self.labelname2 = QtWidgets.QLabel(parent=flames)
        self.labelname2.setGeometry(QtCore.QRect(140, 160, 49, 21))
        self.labelname2.setObjectName("labelname2")
        self.labelname2.setStyleSheet("background-color: rgb(123, 123, 123);color: black; font-size: 14px;")

        self.input1 = QtWidgets.QLineEdit(parent=flames)
        self.input1.setGeometry(QtCore.QRect(220, 120, 113, 24))
        self.input1.setObjectName("input1")
        self.input1.setStyleSheet("color: black; font-size: 14px;")

        self.input2 = QtWidgets.QLineEdit(parent=flames)
        self.input2.setGeometry(QtCore.QRect(220, 160, 113, 24))
        self.input2.setObjectName("input2")
        self.input2.setStyleSheet("color: black; font-size: 14px;")

        self.pushButton = QtWidgets.QPushButton(parent=flames)
        self.pushButton.setGeometry(QtCore.QRect(240, 210, 80, 24))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet("background-color: green;text-align: center;color : black; font-size: 14px;")

        self.outputlabel = QtWidgets.QLabel(parent=flames)
        self.outputlabel.setGeometry(QtCore.QRect(100, 270, 600, 40))
        self.outputlabel.setObjectName("outputlabel")
        self.outputlabel.setStyleSheet("color : black; font-size: 16px;")

        self.pushButton.clicked.connect(self.display)

        self.retranslateUi(flames)
        QtCore.QMetaObject.connectSlotsByName(flames)
    
    def display(self):
        Name1 = self.input1.text().lower()
        Name2 = self.input2.text().lower()
        name1 = Name1.replace(" ", "")
        name2 = Name2.replace(" ", "")

        for i in name1:
            for j in name2:
                if i==j:
                    name1 = name1.replace(i, "", 1)
                    name2 = name2.replace(j, "", 1)
                    break
        count = len(name1+name2)

        if count>0:
            list = ["FRIEND", "LOVER", "AFFECTION", "MARRIAGE", "ENEMIES", "SIBILINGS"]
            while len(list) > 1:
                c = count%len(list)
                delete_index = c-1
                if delete_index>=0:
                    left = list[:delete_index]
                    right = list[delete_index+1:]
                    list = right + left 
                else:
                    list = list[:len(list)-1]       
            output = f"The Relationship between {Name1} and {Name2} is: {list[0]}"
            print("The Relationship between ",Name1, " and ",Name2," is: ",list[0])
        else:
            print(Name1," and ",Name2," are have same Characters, Please choose different names.")
            output = f"Name1 and Name2 are have same Characters, Please choose different names."
        self.outputlabel.setText(output)


    def retranslateUi(self, flames):
        _translate = QtCore.QCoreApplication.translate
        flames.setWindowTitle(_translate("flames", "flames"))
        self.labelname1.setText(_translate("flames", "Name 1"))
        self.labelname2.setText(_translate("flames", "Name 2"))
        self.pushButton.setText(_translate("flames", "Generate"))
        self.outputlabel.setText(_translate("flames", ""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    flames = QtWidgets.QWidget()
    ui = Ui_flames()
    ui.setupUi(flames)
    flames.show()
    sys.exit(app.exec())
